version: '3.8'

services:
  server:
    # env_file:
    #   - skribbl.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build: ./Skribbl
    ports:
      - "5000:80"
  frontend:
    stdin_open: true
    build:
      context: ./skribbl-client
      dockerfile: Dockerfile
    volumes:
      - ./skribbl-client:/app/client
      - ./skribbl-client/node_modules:/app/client/node_modules
    ports:
      - "3000:3000"